[build]
  command = "npm run build"
  publish = "dist"

# Redirect all routing to the React index.html for Single Page Application support
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
